// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MxmdDev.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MxmdDev.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331011812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MxmdDev.Api.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Full post content goes here.",
                            Excerpt = "Why removing features is often the most sophisticated engineering decision you can make.",
                            PublishedAt = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "functional-minimalism-system-design",
                            Tags = new[] { "MINIMALISM", "ESSAYS" },
                            Title = "The Case for Functional Minimalism in System Design"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Full post content goes here.",
                            Excerpt = "Exploring allocation strategies and GC pressure in constrained runtime environments on the edge.",
                            PublishedAt = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "memory-management-edge-computing",
                            Tags = new[] { "PERFORMANCE", "SYSTEMS" },
                            Title = "Memory Management in Modern Edge Computing"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Full post content goes here.",
                            Excerpt = "How readability, whitespace, and naming conventions converge into a form of engineering craft.",
                            PublishedAt = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "aesthetic-of-clean-code",
                            Tags = new[] { "CRAFT", "DX" },
                            Title = "The Aesthetic of Clean Code: A Visual Perspective"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Full post content goes here.",
                            Excerpt = "An exploration into how deterministic logic governs high-concurrency environments, and why state drift is the entropy of the modern web stack.",
                            PublishedAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "physics-of-finite-state-machines",
                            Tags = new[] { "ARCHITECTURE", "SCALABILITY" },
                            Title = "The Physics of Finite State Machines in Distributed Systems"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Full post content goes here.",
                            Excerpt = "Using Result types and functional patterns to treat errors as first-class citizens rather than exceptional flow interruptions in your TypeScript codebase.",
                            PublishedAt = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "type-safe-error-handling",
                            Tags = new[] { "TYPESCRIPT", "DX" },
                            Title = "Type-Safe Error Handling: Moving Beyond Try-Catch"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Full post content goes here.",
                            Excerpt = "Analyzing how closure-heavy components and dangling event listeners can degrade long-lived single-page applications over time.",
                            PublishedAt = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "memory-leaks-virtual-dom",
                            Tags = new[] { "PERFORMANCE", "REACT" },
                            Title = "Memory Leaks and the Virtual DOM: A Post-Mortem"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Full post content goes here.",
                            Excerpt = "Why choosing stable, mature technologies over the latest trend is often the most innovative decision a senior engineer can make for a project's lifecycle.",
                            PublishedAt = new DateTime(2024, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "case-for-boring-software",
                            Tags = new[] { "MINIMALISM", "ESSAYS" },
                            Title = "The Case for Boring Software"
                        });
                });

            modelBuilder.Entity("MxmdDev.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<string>("LiveDemoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A decentralized processing engine for distributed microservices with automated fault-recovery systems.",
                            GitHubUrl = "https://github.com/mxmd-dev/neural-core-v2",
                            Status = "Stable",
                            Tags = new[] { "REST", "GRPC", "KUBERNETES" },
                            Title = "NEURAL_CORE_V2"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A low-latency component library designed for high-frequency trading dashboards and real-time data visualization.",
                            GitHubUrl = "https://github.com/mxmd-dev/stratos-ui",
                            LiveDemoUrl = "https://stratos-ui.mxmd.dev",
                            Status = "Stable",
                            Tags = new[] { "TYPESCRIPT", "WEBASSEMBLY", "TAILWIND" },
                            Title = "STRATOS_UI"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-performance indexing service for large-scale document storage systems with semantic search capabilities.",
                            GitHubUrl = "https://github.com/mxmd-dev/omni-search-idx",
                            Status = "Beta",
                            Tags = new[] { "GO", "ELASTIC", "VECTOR DB" },
                            Title = "OMNI_SEARCH_IDX"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A high-performance mathematical engine designed for real-time vector quantization. Optimized for edge computing environments with minimal memory footprint.",
                            GitHubUrl = "https://github.com/mxmd-dev/vector-core-alpha",
                            LiveDemoUrl = "https://vector-core.mxmd.dev",
                            Status = "Stable",
                            Tags = new[] { "RUST", "WEBASSEMBLY", "GLSL" },
                            Title = "VECTOR CORE ALPHA"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Experimental implementation of self-organizing feature maps for visualizing high-dimensional network traffic in real-time structural grids.",
                            GitHubUrl = "https://github.com/mxmd-dev/neural-lattice",
                            LiveDemoUrl = "https://neural-lattice.mxmd.dev",
                            Status = "Beta",
                            Tags = new[] { "PYTHON", "PYTORCH", "DOCKER" },
                            Title = "NEURAL LATTICE"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The design system driving this very site. Focused on brutalist precision, tonal layering, and mathematical layout consistency across devices.",
                            GitHubUrl = "https://github.com/mxmd-dev/monolith-ui",
                            LiveDemoUrl = "https://mxmd.dev",
                            Status = "Stable",
                            Tags = new[] { "TYPESCRIPT", "TAILWIND", "NEXT.JS" },
                            Title = "MONOLITH UI"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Low-level system monitoring tool leveraging eBPF for zero-overhead observability into kernel-level task scheduling and I/O latency.",
                            GitHubUrl = "https://github.com/mxmd-dev/kernel-watch",
                            Status = "Archived",
                            Tags = new[] { "C++", "LINUX", "EBPF" },
                            Title = "KERNEL WATCH"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
